matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
    - eval "${MATRIX_EVAL}"
language: python
sudo: false
env:
  - BOTO_CONFIG=/dev/null
python:
  - "3.6"
install:
  - python setup.py develop -q
before_script: cd tests
script:
  - pip freeze
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pytest --runintegration; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pytest; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pip install black; black --check .; fi'
